### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by isyinxian** [yusixian/cos_blogs#19]
up主 你好 我fork了你的blog项目，但是vercel的网站dns污染太严重了，所以我去cf page部署了这个项目，但是部署成功，但是访问不了是什么原因，是要设置根目录什么的吗
![image](https://github.com/yusixian/cos_blogs/assets/85432589/e8d9daaf-a3a8-4672-95bc-9fd2aa421dc6)

**Comment by yusixian** [comment]
要有hexo-cli，可以看看这篇文章：[Hexo + GitPage 搭建个人博客](https://www.jianshu.com/p/d9dff0bf5da5)
如果vercel部署的话是有hexo模板的，如图：
![image](https://github.com/yusixian/cos_blogs/assets/43498495/5b5cee26-d389-4ff2-9743-bdded736a449)

**Comment by isyinxian** [comment]
> > up主 你好 我fork了你的blog项目，但是vercel的网站dns污染太严重了，所以我去cf page部署了这个项目，但是部署成功，但是访问不了是什么原因，是要设置根目录什么的吗 ![image](https://usercontent.githubfast.com/user-images/85432589/277711120-e8d9daaf-a3a8-4672-95bc-9fd2aa421dc6.png)
> 
> [Hexo + GitPage 搭建个人博客](https://www.jianshu.com/p/d9dff0bf5da5)[Hexo + GitPage 搭建个人博客](https://www.jianshu.com/p/d9dff0bf5da5) ![image](https://usercontent.githubfast.com/user-images/43498495/277712587-5b5cee26-d389-4ff2-9743-bdded736a449.png)

up你好，为什么我按照教程来一步步搭建hexo，然后在添加github page 但是本地的可以看，github page的显示404，仓库也有，我还看了github page的404的docx，但是好像都没问题，然后我网上也找了一些相似的问题解答，但是还是不行，然后我删了几次仓库，又按照hexo官方的建站文档来，最后还是不行，请问up主知道这是什么原因嘛，知道的话麻烦up主告知一下
![image](https://github.com/yusixian/cos_blogs/assets/85432589/51abc0e7-e8bb-4b62-a906-c26c558d57e4)
![image](https://github.com/yusixian/cos_blogs/assets/85432589/6280c251-ed38-43d0-8755-b7da2fcd68ee)
![image](https://github.com/yusixian/cos_blogs/assets/85432589/7fbb2327-2b92-41d0-a696-c152f273e28c)

**Comment by yusixian** [comment]
查下这里 <img width="930" alt="image" src="https://github.com/yusixian/cos_blogs/assets/43498495/eab04b26-8eb1-43db-b58c-a7b9b54b8f85"> 有没有设置对应分支

**Comment by isyinxian** [comment]
> 查下这里 <img alt="image" width="930" src="https://usercontent.githubfast.com/user-images/43498495/278316907-eab04b26-8eb1-43db-b58c-a7b9b54b8f85.png"> 有没有设置对应分支

![image](https://github.com/yusixian/cos_blogs/assets/85432589/234d868a-aa3a-431b-ab9c-491ee2d1e849)
有的，前几次我试过了，然后我现在又试过了，还是没有用，有点奇怪，一般来说本地装好了hexo，然后填完了仓库地址，然后发布了，就可以先看到了，但是我这个好像不知道有什么问题
